voiceupbw/voiceUpPost/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('<str:username>/feed/', views.feed, name='feed'),
    path('<int:id>/', views.post_detail, name="detail"),
]

voiceupbw/voiceupbw/urls.py
from django.contrib import admin
from django.urls import path, include
from voiceupprofile import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.frontpage, name='frontpage'),
    path('', include('voiceupprofile.urls')),
    path('', include('voiceUpPost.urls')),
]

voiceupbw/voiceupprofile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('signout/', views.signout, name='signout'),
    path('<str:username>/follows/', views.follows, name='follows'),
    path('<str:username>/followers/', views.followers, name='following'),
    path('<str:username>/follow/', views.follow, name='follow'),
    path('<str:username>/stopfollow/', views.stopfollow, name='stopfollow'),
    path('<str:username>/', views.profile, name="profile"),
]

voiceupbw/const/models.py
from django.db import models

# Create your models here.

voiceupbw/voiceUpPost/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class VoiceUpPost(models.Model):
    user = models.ForeignKey(User, related_name='voiceuppost', on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Comment(models.Model):
    post = models.ForeignKey(VoiceUpPost, related_name='comments', on_delete=models.CASCADE)
    user = models.CharField(max_length=250)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    def approved(self):
        self.approved = True
        self.save()

    def __Str__(self):
        return self.user

voiceupbw/voiceupprofile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class VoiceUpProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    district = models.CharField(max_length=100)
    isPolitician = models.BooleanField(default=False)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False)


User.voiceupprofile = property(lambda u: VoiceUpProfile.objects.get_or_create(user=u)[0])

voiceupbw/voiceUpPost/forms.py
# Import django forms and models

from django import forms
from .models import VoiceUpPost, Comment


class VoiceUpPostForm(forms.ModelForm):

    body = forms.CharField(required=True, widget=forms.widgets.Textarea(attrs={'placeholder': 'Post', 'class': 'form-control'}))

    class Meta:
        model = VoiceUpPost
        exclude = ('user',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'body',)

voiceupbw/voiceupprofile/forms.py
# Import django forms and models

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.utils.html import strip_tags


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}))
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password Confirmation', 'class': 'form-control'}))

    class Meta:
        fields = ['email', 'username', 'first_name', 'last_name', 'password1', 'password2']
        model = User


class SigninForm(AuthenticationForm):
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))

voiceupbw/const/views.py
from django.shortcuts import render

# Create your views here.

voiceupbw/voiceUpPost/views.py
from django.shortcuts import render, redirect
from .models import VoiceUpPost, Comment
from django.contrib.auth.decorators import login_required


@login_required
def feed(request, username):
    userids = []
    for id in request.user.voiceupprofile.follows.all():
        userids.append(id.user)

    userids.append(request.user.id)
    posts = VoiceUpPost.objects.filter(user_id__in=userids)[0:25]

    return render(request, 'voiceUpPost/templates/feed.html', {'posts': posts})


def post_detail(request, username, id):
    post = VoiceUpPost.objects.get(id=id)
    comments = Comment.objects.get(post=id)
    return render(request, 'post_detail.html', {'comments': comments, 'post': post})

voiceupbw/voiceupprofile/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from voiceupprofile.forms import SignupForm, SigninForm
from voiceUpPost.forms import VoiceUpPostForm


# Views
@login_required
def profile(request, username):
    if request.user.is_authenticated:
        user = User.objects.get(username=username)

        if request.method == 'POST':
            form = VoiceUpPostForm(data=request.POST)

            if form.is_valid():
                voiceuppost = form.save(commit=False)
                voiceuppost.user = request.user
                voiceuppost.save()

                redirecturl = request.POST.get('redirect', '/')

                return redirect(redirecturl)
        else:
            form = VoiceUpPostForm()

        return render(request, 'profile.html', {'form': form, 'user': user})
    else:
        return redirect('/')


def frontpage(request):
    if request.user.is_authenticated:
        return redirect('/' + request.user.username + '/')
    else:
        if request.method == 'POST':
            if 'signupform' in request.POST:
                signupform = SignupForm(data=request.POST)
                signinform = SigninForm()

                if signupform.is_valid():
                    username = signupform.cleaned_data['username']
                    password = signupform.cleaned_data['password1']
                    signupform.save()
                    user = authenticate(username=username, password=password)
                    login(request, user)
                    return redirect('/')
            else:
                signinform = SigninForm(data=request.POST)
                signupform = SignupForm()

                if signinform.is_valid():
                    login(request, signinform.get_user())
                    return redirect('/')
        else:
            signupform = SignupForm()
            signinform = SigninForm()

        return render(request, 'frontpage.html', {'signupform': signupform, 'signinform': signinform})


@login_required
def signout(request):
    logout(request)
    return redirect('/')


@login_required
def follows(request, username):
    user = User.objects.get(username=username)
    profiles = user.voiceupprofile.follows.all()

    return render(request, 'users.html', {'title': 'Follows', 'profiles': profiles})


@login_required
def followers(request, username):
    user = User.objects.get(username=username)
    profiles = user.voiceupprofile.followed_by.all()

    return render(request, 'users.html', {'title': 'Followers', 'profiles': profiles})


@login_required
def follow(request, username):
    user = User.objects.get(username=username)
    request.user.voiceupprofile.follows.add(user.voiceupprofile)

    return redirect('/' + user.username + '/')


@login_required
def stopfollow(request, username):
    user = User.objects.get(username=username)
    request.user.voiceupprofile.follows.remove(user.voiceupprofile)

    return redirect('/' + user.username + '/')

voiceupbw/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>VoiceUpBW</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body style="padding-top: 80px;">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'profile:profile' username=request.user %}">VoiceUpBW</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile:profile' username=request.user %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:feed' username=request.user %}">Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile:signout' %}">Sign out</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- End Navbar -->

    <!-- Main -->
    <main role="main" class="container">
      {% block main %}
      {% endblock %}
    </main>
    <!-- End Main -->

    <!-- Scripts - Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

voiceupbw/templates/frontpage.html
{% extends 'templates/base.html' %}

{% block main %}
<div class="row">
  <div class="col-12">
    <h1>Welcome to VoiceUp</h1>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-6">
    <h2>Sign in</h2>

    {% if signinform.errors %}
      {% for field in signinform %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            <b>{{ error|escape }}</b>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in signinform.non_field_errors %}
        <div class="alert alert-danger">
          <b>{{ error|escape }}</b>
        </div>
      {% endfor %}
    {% endif %}

    <form action="." method="post">
      {% csrf_token %}

      {% for field in signinform %}
        <div class="form-group">
          {{ field }}
        </div>
      {% endfor %}

      <input type="submit" value="Sign in" name="signinform" class="btn btn-primary">
    </form>
  </div>

  <div class="col-6">
    <h3>Don't have an account yet?</h3>

    {% if signupform.non_field_errors %}
      <div class="alert danger">
        {{ signupform.non_field_errors }}
      </div>
    {% endif %}

    {% if signupform.errors %}
      {% for field in signupform %}
        {% for error in field.errors %}
          <div class="alert alert-danger">
            <b>{{ error|escape }}</b>
          </div>
        {% endfor %}
      {% endfor %}
      {% for error in signupform.non_field_errors %}
        <div class="alert alert-danger">
          <b>{{ error|escape }}</b>
        </div>
      {% endfor %}
    {% endif %}

    <form action="." method="post">
      {% csrf_token %}

      {% for field in signupform %}
        <div class="form-group">
          {{ field }}
        </div>
      {% endfor %}

      <input type="submit" value="Sign up" name="signupform" class="btn btn-primary">
    </form>
  </div>
</div>
{% endblock %}

voiceupbw/voiceUpPost/templates/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}>

voiceupbw/voiceUpPost/templates/feed.html
{% extends 'templates/base.html' %}

{% block main %}
<div class="row">
  <div class="col-12">
    <h3>Feed</h3>

    {% for post in posts %}
      <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
          <h5 class="card-title"><a href="/{{ post.user.username }}/">@{{ post.user.username }}</a></h5>
          <p class="card-text"><b>{{ post.created_at }}</b> - {{ post.body }}</p>
            <a href="{% url 'post:detail' id=post.id %}">Comment(s)</a>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

voiceupbw/voiceUpPost/templates/post_detail.html
{% extends 'templates/base.html' %}

{% block main %}
<div class="row">
  <div class="col-12">
    <h3>Post Detail</h3>
    <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
          <h5 class="card-title">Post</h5>
          <p class="card-text"><b>{{ post.created_at }}</b> - {{ post.body }}</p>
            <a href="{% url 'add_comment' slug=post.slug %}">Leave a comment</a>
        </div>
      </div>
  </div>
</div>
{% endblock %}

voiceupbw/voiceupprofile/templates/profile.html
{% extends 'templates/base.html' %}

{% block main %}
    <div class="row">
      <!-- Feed -->
      <div class="col-9">
        <h3>@{{ user.username }}</h3>

          <hr>

        <b><a href="/{{ user.username }}/follows/">Follows:</a></b> {{ user.voiceupprofile.follows.count }}
        <b><a href="/{{ user.username }}/followers/">Followers:</a></b> {{ user.voiceupprofile.followed_by.count }}


        {% ifnotequal request.user user %}
          <hr>
          {% if request.user.voiceupprofile in user.voiceupprofile.followed_by.all %}
            <a href="/{{ user.username }}/stopfollow/" class="btn btn-danger">Stop follow</a>
          {% else %}
            <a href="/{{ user.username }}/follow/" class="btn btn-success">Follow</a>
          {% endif %}
        {% endifnotequal %}

        <hr>

        {% if user.voiceuppost.all %}
          {% for post in user.voiceuppost.all %}
            <div class="card" style="margin-bottom: 20px;">
              <div class="card-body">
                <h5 class="card-title">@{{ post.user.username }}</h5>
                <p class="card-text"><b>{{ post.created_at }}</b> - {{ post.body }}</p>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>No Posts yet!</p>
        {% endif %}
      </div>

        {% ifequal request.user user %}
      <!-- Sidebar -->
      <div class="col-3">
        <h3>Add Post</h3>
          {% if form.errors %}
            {% for field in form %}
                {% for error in form.errors %}
                    <div class="alert alert-danger">
                        <b>{{ error|escape }}</b>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <b>{{ error|escape }}</b>
                </div>
            {% endfor %}
        {% endif %}


        <form action="/{{ request.user.username }}/" method="post">
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}

            <input type="hidden" value="{{ request.path }}" name="redirect">
            <input type="submit" value="Post" class="btn btn-primary">
        </form>
      {% endifequal %}
      </div>
    </div>
{% endblock %}

voiceupbw/voiceupprofile/templates/users.html
{% extends 'base.html' %}

{% block main %}
<div>
  <h1>{{ title }}</h1>
  <ul>
    {% for profile in profiles %}
      <li><a href="/{{ profile.user.username }}/">@{{ profile.user.username }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}